version: 0.1.{build}

platform:
  - x64

install:
  - cmd: git submodule update --recursive --init

configuration:
  - Debug

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: cmake --build .
  - cmd: ctest
